SELECT 
  AvailabilityZone, 
  BilledCost * CAST(RAND() * 1000 + 1000 AS INT64) AS BilledCost,
  BillingAccountId,
  BillingAccountName,
  BillingCurrency,
  TIMESTAMP_ADD(BillingPeriodEnd, INTERVAL 365 DAY) AS BillingPeriodEnd,
  TIMESTAMP_ADD(BillingPeriodStart, INTERVAL 365 DAY) AS BillingPeriodStart,
  ChargeCategory,
  ChargeClass,
  ChargeDescription,
  ChargeFrequency,
  TIMESTAMP_ADD(ChargePeriodEnd,  INTERVAL 365 DAY) AS ChargePeriodEnd,
  TIMESTAMP_ADD(ChargePeriodStart, INTERVAL 365 DAY) AS ChargePeriodStart,
  CommitmentDiscountCategory,
  CommitmentDiscountId,
  CommitmentDiscountName,
  CommitmentDiscountStatus,
  CommitmentDiscountType,
  ConsumedQuantity,
  ConsumedUnit,
  ContractedCost,
  ContractedUnitPrice,
  EffectiveCost * 1000 AS EffectiveCost,
  InvoiceIssuerName,
  ListCost * 1000 AS ListCost,
  ListUnitPrice,
  PricingCategory,
  null AS PricingQuantity,
  PricingUnit,
  ProviderName,
  PublisherName,
  RegionId,
  RegionName,
  ResourceId,
  ResourceName,
  ResourceType,
  ServiceCategory,
  -- Id,
  ServiceName,
  SkuId,
  SkuPriceId,
  SubAccountId,
  SubAccountName
FROM `thekitchentable.focus_multicloud.focus_aws`
WHERE EXTRACT(Year FROM ChargePeriodStart) = 2024
AND EXTRACT(Month FROM ChargePeriodStart) <= Extract(Month from current_date())