CREATE OR REPLACE VIEW focus_multicloud.focus_azure_2025 AS (
SELECT
    `BilledCost` * 1000000 AS `BilledCost`,
    `BillingAccountId`,
    `BillingCurrency`,
    `BillingPeriodEnd`,
    `BillingPeriodStart`,
    `ChargeCategory`,
    `ChargeClass`,
    `ChargeDescription`,
    `ChargePeriodEnd`,
    `ChargePeriodStart`,
    `CommitmentDiscountCategory`,
    `CommitmentDiscountId`,
    `CommitmentDiscountName`,
    `ConsumedQuantity`,
    `ConsumedUnit`,
    `ContractedCost`,
    `ContractedUnitPrice`,
    `EffectiveCost` * 1000000 AS `EffectiveCost`,
    `ListCost` * 1000000 AS `ListCost`,
    `ListUnitPrice`,
    `PricingCategory`,
     CAST(`PricingQuantity` AS FLOAT64) AS `PricingQuantity`, 
    `PricingUnit`,
    `ProviderName`,
    `PublisherName`,
    `RegionId`,
    `RegionName`,
    `ResourceId`,
    `ResourceName`,
    `ResourceType`,
    `ServiceCategory`,
    `ServiceName`,
     CAST(`SkuId` AS STRING) AS `SkuId`,
     CAST(`SkuPriceId` AS STRING) AS `SkuPriceID`,
    `SubAccountId`
FROM
    `thekitchentable.focus_multicloud.focus_azure` 
)