-- truncate table thekitchentable.focus_multicloud.focus_azure
CREATE TABLE thekitchentable.focus_multicloud.focus_aws (
AvailabilityZone STRING, 
BilledCost FLOAT64,
BillingAccountId STRING,
BillingAccountName STRING,
BillingCurrency STRING,
BillingPeriodEnd TIMESTAMP,
BillingPeriodStart TIMESTAMP,
ChargeCategory STRING,
ChargeClass STRING,
ChargeDescription STRING,
ChargeFrequency STRING,
ChargePeriodEnd TIMESTAMP,
ChargePeriodStart TIMESTAMP,
CommitmentDiscountCategory STRING,
CommitmentDiscountId STRING,
CommitmentDiscountName STRING,
CommitmentDiscountStatus STRING,
CommitmentDiscountType STRING,
ConsumedQuantity FLOAT64,
ConsumedUnit STRING,
ContractedCost FLOAT64,
ContractedUnitPrice FLOAT64,
EffectiveCost FLOAT64,
InvoiceIssuerName STRING,
ListCost FLOAT64,
ListUnitPrice FLOAT64,
PricingCategory STRING,
PricingQuantity FLOAT64,
PricingUnit STRING,
ProviderName STRING,
PublisherName STRING,
RegionId STRING,
RegionName STRING,
ResourceId STRING,
ResourceName STRING,
ResourceType STRING,
ServiceCategory STRING,
-- Id,
ServiceName STRING,
SkuId STRING,
SkuPriceId STRING,
SubAccountId STRING,
SubAccountName STRING
);

INSERT INTO thekitchentable.focus_multicloud.focus_azure (
AvailabilityZone, 
BilledCost,
BillingAccountId,
BillingAccountName,
BillingCurrency,
BillingPeriodEnd,
BillingPeriodStart,
ChargeCategory,
ChargeClass,
ChargeDescription,
ChargeFrequency,
ChargePeriodEnd,
ChargePeriodStart,
CommitmentDiscountCategory,
CommitmentDiscountId,
CommitmentDiscountName,
CommitmentDiscountStatus,
CommitmentDiscountType,
ConsumedQuantity,
ConsumedUnit,
ContractedCost,
ContractedUnitPrice,
EffectiveCost,
InvoiceIssuerName,
ListCost,
ListUnitPrice,
PricingCategory,
PricingQuantity,
PricingUnit,
ProviderName,
PublisherName,
RegionId,
RegionName,
ResourceId,
ResourceName,
ResourceType,
ServiceCategory,
-- Id,
ServiceName,
SkuId,
SkuPriceId,
SubAccountId,
SubAccountName
)
SELECT 
 "" AS `AvailabilityZone`, -- CHECK
  lineItem_UnBlendedCost `BilledCost`, -- CHECK
  billingAccountId `BillingAccountId`,
  billingAccountName `BillingAccountName` ,
  billingCurrency `BillingCurrency`,
  billingPeriodEndDate `BillingPeriodEnd`,
  billingPeriodStartDate `BillingPeriodStart`,
  chargeType `ChargeCategory`, -- CHECK
  "" `ChargeClass` ,
  "" `ChargeDescription`,
  CASE WHEN lineItem_LineItemType = 'Usage' then 'Usage-Based' else NULL end `ChargeFrequency`,
  lineItem_UsageEndDate `ChargePeriodEnd`,
  lineItem_UsageStartDate `ChargePeriodStart`,
  "" `CommitmentDiscountCategory`,
  "" `CommitmentDiscountId`,
  "" `CommitmentDiscountName`,
  "" `CommitmentDiscountStatus`,
  "" `CommitmentDiscountType` ,
  CAST(lineItem_UsageAmount AS String) `ConsumedQuantity`,
  pricing_unit `ConsumedUnit` ,
  CAST(lineItem_UnBlendedCost AS String) `ContractedCost`,
  CAST(lineItem_UnblendedRate AS STRING) `ContractedUnitPrice`,
  lineItem_BlendedCost `EffectiveCost`,
  "Amazon Web Services, Inc." `InvoiceIssuerName`,
  pricing_publicOnDemandCost `ListCost`,
  CAST(pricing_publicOnDemandRate AS STRING) `ListUnitPrice`,
  "Standard" `PricingCategory`,
  pricing_unit`PricingQuantity`,
  pricing_unit `PricingUnit`,
  "AWS" `ProviderName` ,
  lineItem_LegalEntity `PublisherName`,
  product_region `RegionId` ,
  product_location `RegionName` ,
  lineItem_ResourceId `ResourceId`,
  "" `ResourceName`,
  "" `ResourceType`,
  product_productfamily `ServiceCategory` ,
  -- `Id` bigint unsigned NOT NULL AUTO_INCREMENT,
  product_productname `ServiceName`,
  product_sku `SkuId` ,
  pricing_ratecode `SkuPriceId`,
  CAST(lineitem_usageaccountid AS STRING) `SubAccountId` ,
 CAST(lineitem_usageaccountid  AS STRING)`SubAccountName`
  -- NULL AS `Tags`

 FROM `eaf-barong-da-qa.billing.aws_imported`