CREATE OR REPLACE VIEW focus_multicloud.focus_union AS (
SELECT
    `BilledCost`,
    `BillingAccountId`,
    `BillingCurrency`,
    `BillingPeriodEnd`,
    `BillingPeriodStart`,
    `ChargeCategory`,
    `ChargeClass`,
    `ChargeDescription`,
    `ChargePeriodEnd`,
    `ChargePeriodStart`,
    `CommitmentDiscountCategory`,
    `CommitmentDiscountId`,
    `CommitmentDiscountName`,
     CAST(`ConsumedQuantity` AS FLOAT64) AS `ConsumedQuantity`,
    `ConsumedUnit`,
     CAST(`ContractedCost` AS FLOAT64) AS `ContractedCost`,
     CAST(`ContractedUnitPrice` AS FLOAT64) AS `ContractedUnitPrice`,
    `EffectiveCost`,
    `ListCost`,
     CAST(`ListUnitPrice` AS FLOAT64) AS `ListUnitPrice`, 
     `PricingCategory`,
     `PricingQuantity`,
    `PricingUnit`,
    `ProviderName`,
    `PublisherName`,
    `RegionId`,
    `RegionName`,
    `ResourceId`,
    `ResourceName`,
    `ResourceType`,
    `ServiceCategory`,
    `ServiceName`,
    `SkuId`,
    `SkuPriceId`,
    `SubAccountId`
FROM
    `thekitchentable.focus_multicloud.focus_aws_2025` 

UNION ALL

SELECT
    `BilledCost`,
    `BillingAccountId`,
    `BillingCurrency`,
    `BillingPeriodEnd`,
    `BillingPeriodStart`,
    `ChargeCategory`,
    `ChargeClass`,
    `ChargeDescription`,
    `ChargePeriodEnd`,
    `ChargePeriodStart`,
    `CommitmentDiscountCategory`,
    `CommitmentDiscountId`,
    `CommitmentDiscountName`,
    `ConsumedQuantity`,
    `ConsumedUnit`,
    `ContractedCost`,
    `ContractedUnitPrice`,
    `EffectiveCost`,
    `ListCost`,
    `ListUnitPrice`,
    `PricingCategory`,
    -- TODO: once AWS PricingQuantity has been verified to numeric value, change to FLOAT64
     CAST(`PricingQuantity` AS FLOAT64) AS `PricingQuantity`, 
    `PricingUnit`,
    `ProviderName`,
    `PublisherName`,
    `RegionId`,
    `RegionName`,
    `ResourceId`,
    `ResourceName`,
    `ResourceType`,
    `ServiceCategory`,
    `ServiceName`,
     CAST(`SkuId` AS STRING) AS `SkuId`,
     CAST(`SkuPriceId` AS STRING) AS `SkuPriceID`,
    `SubAccountId`
FROM
    `thekitchentable.focus_multicloud.focus_azure` 

UNION ALL

SELECT
     CAST(`BilledCost` AS FLOAT64) AS `BilledCost`,
    `BillingAccountId`,
    `BillingCurrency`,
    `BillingPeriodEnd`,
    `BillingPeriodStart`,
    `ChargeCategory`,
    `ChargeClass`,
    `ChargeDescription`,
    `ChargePeriodEnd`,
    `ChargePeriodStart`,
    `CommitmentDiscountCategory`,
    `CommitmentDiscountId`,
    `CommitmentDiscountName`,
     CAST(`ConsumedQuantity` AS FLOAT64) AS `ConsumedQuantity`,
    `ConsumedUnit`,
     CAST(`ContractedCost` AS FLOAT64) AS `ContractedCost`,
     CAST(`ContractedUnitPrice` AS FLOAT64) AS `ContractedUnitPrice`,
     CAST(`EffectiveCost` AS FLOAT64) AS `EffectiveCost`,
     CAST(`ListCost` AS FLOAT64) AS `ListCost`,
     CAST(`ListUnitPrice` AS FLOAT64) AS `ListUnitPrice`,
    `PricingCategory`,
     CAST(`PricingQuantity` AS FLOAT64) AS `PricingQuantity`, 
    `PricingUnit`,
    `ProviderName`,
    `PublisherName`,
    `RegionId`,
    `RegionName`,
    `ResourceId`,
    `ResourceName`,
    `ResourceType`,
     ARRAY_TO_STRING(`ServiceCategory`, ', ') AS `ServiceCategory`,
    `ServiceName`,
    `SkuId`,
    `SkuPriceId`,
    `SubAccountId`
FROM
    `thekitchentable.focus_multicloud.focus_gcp`
)